#!/bin/sh
#
# Author:   Dimitris Deyannis
# E-mail:   d.deyannis@gmail.com
# Modified: Fri 28 Oct 2019

# include global conf
#. /etc/ksh.kshrc

# EMACS mode
set -o emacs

# fix ksh & st delete key
bind -m '^[[P'='^[[3~'

# minimal command prompt
PS1='\u@\h -> '

# try ls with colors and human readable sizes
if type colorls > /dev/null
then
	alias ls='colorls -h -G'
fi

# update locate db in a Linux fashion 
alias updatedb='/usr/libexec/locate.updatedb'

# pastebin
alias sprunge='curl -F "sprunge=<-" http://sprunge.us'

# update ksh 
alias kshrc=". ~/.kshrc"
