#!/bin/sh
#
# Author:   Dimitris Deyannis
# E-mail:   d.deyannis@gmail.com
# Modified: Thu 12 Oct 2023 @ 01:56:30 +0300


# include global conf
#. /etc/ksh.kshrc

# vim as default editor
export VISUAL=vim

# EMACS mode
set -o emacs

# fix ksh & st delete key
bind -m '^[[P'='^[[3~'

# minimal command prompt
PS1='\u@\h -> '

# doas
alias doas="doas "

# try ls with colors and human readable sizes
if type colorls > /dev/null
then
	alias ls="colorls -Gh"
fi

# check temperatures
alias lstemp="sysctl hw.sensors"

# update locate db in a Linux fashion 
alias updatedb="/usr/libexec/locate.updatedb"

# list active services
alias lservice="echo '--- Services ---'; rcctl ls on; echo '----------------'"
# pastebin
alias sprunge="curl -F \"sprunge=<-\" http://sprunge.us"

# enable hyper-threading
alias ht_on="sysctl hw.smt=1"

# disable hyper-threading
alias ht_off="sysctl hw.smt=0"

# enable video recording
alias vrec_on="sysctl kern.video.record=1"

# disable video recording
alias vrec_off="sysctl kern.video.record=0"

# enable audio recording
alias arec_on="sysctl kern.audio.record=1"

# disable audio recording
alias arec_off="sysctl kern.audio.record=0"

# daemonize a job
alias daemon="daemon"
function daemon {
	(exec "$@" &) > /dev/null 2>&1
}

# update ksh 
alias kshrc=". ~/.kshrc"
